# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalculatorBox.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CalculatorBox(object):
    def setupUi(self, CalculatorBox):
        CalculatorBox.setObjectName("CalculatorBox")
        CalculatorBox.resize(1400, 680)
        CalculatorBox.setStyleSheet("#CalculatorBox{background-color: rgb(190, 190, 190)}")
        self.centralwidget = QtWidgets.QWidget(CalculatorBox)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(CalculatorBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 80, 40))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(CalculatorBox)
        self.label_2.setGeometry(QtCore.QRect(260, 40, 90, 40))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(CalculatorBox)
        self.label_3.setGeometry(QtCore.QRect(520, 40, 90, 40))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(CalculatorBox)
        self.label_4.setGeometry(QtCore.QRect(780, 40, 90, 40))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(CalculatorBox)
        self.label_5.setGeometry(QtCore.QRect(1040, 40, 90, 40))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(CalculatorBox)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 80, 40))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(CalculatorBox)
        self.label_7.setGeometry(QtCore.QRect(260, 90, 90, 40))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(CalculatorBox)
        self.label_8.setGeometry(QtCore.QRect(520, 90, 90, 40))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(CalculatorBox)
        self.label_9.setGeometry(QtCore.QRect(780, 90, 90, 40))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(CalculatorBox)
        self.label_10.setGeometry(QtCore.QRect(150, 150, 130, 40))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(CalculatorBox)
        self.label_11.setGeometry(QtCore.QRect(400, 150, 20, 40))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(CalculatorBox)
        self.label_12.setGeometry(QtCore.QRect(505, 150, 50, 40))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(CalculatorBox)
        self.label_13.setGeometry(QtCore.QRect(640, 150, 50, 40))
        self.label_13.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(CalculatorBox)
        self.label_14.setGeometry(QtCore.QRect(670, 150, 90, 40))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(CalculatorBox)
        self.label_15.setGeometry(QtCore.QRect(880, 150, 90, 40))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(CalculatorBox)
        self.label_16.setGeometry(QtCore.QRect(670, 200, 90, 40))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(CalculatorBox)
        self.label_17.setGeometry(QtCore.QRect(120, 200, 160, 40))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(CalculatorBox)
        self.label_18.setGeometry(QtCore.QRect(400, 200, 20, 40))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(CalculatorBox)
        self.label_19.setGeometry(QtCore.QRect(505, 200, 50, 40))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(CalculatorBox)
        self.label_20.setGeometry(QtCore.QRect(640, 200, 50, 40))
        self.label_20.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(CalculatorBox)
        self.label_21.setGeometry(QtCore.QRect(880, 200, 90, 40))
        self.label_21.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(CalculatorBox)
        self.label_22.setGeometry(QtCore.QRect(120, 250, 160, 40))
        self.label_22.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(CalculatorBox)
        self.label_23.setGeometry(QtCore.QRect(400, 250, 20, 40))
        self.label_23.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(CalculatorBox)
        self.label_24.setGeometry(QtCore.QRect(505, 250, 50, 40))
        self.label_24.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(CalculatorBox)
        self.label_25.setGeometry(QtCore.QRect(640, 250, 50, 40))
        self.label_25.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")

        self.label_36 = QtWidgets.QLabel(CalculatorBox)
        self.label_36.setGeometry(QtCore.QRect(670, 250, 90, 40))
        self.label_36.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")

        self.label_26 = QtWidgets.QLabel(CalculatorBox)
        self.label_26.setGeometry(QtCore.QRect(880, 250, 90, 40))
        self.label_26.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(CalculatorBox)
        self.label_27.setGeometry(QtCore.QRect(150, 310, 150, 40))
        self.label_27.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")

        self.label_37 = QtWidgets.QLabel(CalculatorBox)
        self.label_37.setGeometry(QtCore.QRect(550, 310, 150, 40))
        self.label_37.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")

        self.label_28 = QtWidgets.QLabel(CalculatorBox)
        self.label_28.setGeometry(QtCore.QRect(150, 360, 150, 40))
        self.label_28.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(CalculatorBox)
        self.label_29.setGeometry(QtCore.QRect(550, 360, 150, 40))
        self.label_29.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(CalculatorBox)
        self.label_30.setGeometry(QtCore.QRect(150, 410, 150, 40))
        self.label_30.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(CalculatorBox)
        self.label_31.setGeometry(QtCore.QRect(550, 410, 150, 40))
        self.label_31.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(CalculatorBox)
        self.label_32.setGeometry(QtCore.QRect(150, 460, 150, 40))
        self.label_32.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")

        self.label_33 = QtWidgets.QLabel(CalculatorBox)
        self.label_33.setGeometry(QtCore.QRect(550, 460, 150, 40))
        self.label_33.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(CalculatorBox)
        self.label_34.setGeometry(QtCore.QRect(150, 510, 150, 40))
        self.label_34.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(CalculatorBox)
        self.label_35.setGeometry(QtCore.QRect(550, 510, 150, 40))
        self.label_35.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")

        self.cindexEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.cindexEdit.setGeometry(QtCore.QRect(100, 40, 160, 40))
        self.cindexEdit.setDragEnabled(False)
        self.cindexEdit.setClearButtonEnabled(True)
        self.cindexEdit.setObjectName("cindexEdit")

        self.clientEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.clientEdit.setGeometry(QtCore.QRect(360, 40, 160, 40))
        self.clientEdit.setObjectName("clientEdit")
        self.clientEdit.setReadOnly(True)

        self.dateEdit = QtWidgets.QDateEdit(CalculatorBox)
        self.dateEdit.setGeometry(QtCore.QRect(620, 40, 160, 40))
        self.dateEdit.setObjectName("dateEdit")

        self.cnumberEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.cnumberEdit.setGeometry(QtCore.QRect(880, 40, 160, 40))
        self.cnumberEdit.setDragEnabled(False)
        self.cnumberEdit.setClearButtonEnabled(True)
        self.cnumberEdit.setObjectName("cnumberEdit")

        self.indexEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.indexEdit.setGeometry(QtCore.QRect(1140, 40, 160, 40))
        self.indexEdit.setDragEnabled(False)
        self.indexEdit.setClearButtonEnabled(True)
        self.indexEdit.setObjectName("indexEdit")

        self.guihaoEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.guihaoEdit.setGeometry(QtCore.QRect(100, 90, 160, 40))
        self.guihaoEdit.setDragEnabled(False)
        self.guihaoEdit.setClearButtonEnabled(True)
        self.guihaoEdit.setObjectName("guihaoEdit")

        self.baolaijianshuEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.baolaijianshuEdit.setGeometry(QtCore.QRect(360, 90, 160, 40))
        self.baolaijianshuEdit.setClearButtonEnabled(True)
        self.baolaijianshuEdit.setValidator(QtGui.QIntValidator())
        self.baolaijianshuEdit.setObjectName("baolaijianshuEdit")

        self.tiguiriqiEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.tiguiriqiEdit.setGeometry(QtCore.QRect(620, 90, 160, 40))
        self.tiguiriqiEdit.setClearButtonEnabled(True)
        self.tiguiriqiEdit.setObjectName("tiguiriqiEdit")

        self.zuguihaoEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.zuguihaoEdit.setGeometry(QtCore.QRect(880, 90, 160, 40))
        self.zuguihaoEdit.setClearButtonEnabled(True)
        self.zuguihaoEdit.setObjectName("zuguihaoEdit")

        self.zuguiriqi1Edit = QtWidgets.QDateEdit(CalculatorBox)
        self.zuguiriqi1Edit.setGeometry(QtCore.QRect(300, 150, 100, 40))
        self.zuguiriqi1Edit.setObjectName("zuguiriqiEdit1")
        
        self.zuguiriqi2Edit = QtWidgets.QDateEdit(CalculatorBox)
        self.zuguiriqi2Edit.setGeometry(QtCore.QRect(420, 150, 100, 40))
        self.zuguiriqi2Edit.setObjectName("zuguiriqi2Edit")

        self.zuguidateEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.zuguidateEdit.setGeometry(QtCore.QRect(560, 150, 100, 40))
        self.zuguidateEdit.setClearButtonEnabled(True)
        self.zuguidateEdit.setValidator(QtGui.QIntValidator())
        self.zuguidateEdit.setObjectName("zuguidateEdit")

        self.danjia_1Edit = QtWidgets.QLineEdit(CalculatorBox)
        self.danjia_1Edit.setGeometry(QtCore.QRect(770, 150, 120, 40))
        self.danjia_1Edit.setClearButtonEnabled(True)
        self.danjia_1Edit.setValidator(QtGui.QIntValidator())
        self.danjia_1Edit.setObjectName("danjia_1Edit")

        self.zuguifeiEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.zuguifeiEdit.setGeometry(QtCore.QRect(980, 150, 160, 40))
        self.zuguifeiEdit.setClearButtonEnabled(True)
        self.zuguifeiEdit.setObjectName("zuguifeiEdit")

        self.danjia_2Edit = QtWidgets.QLineEdit(CalculatorBox)
        self.danjia_2Edit.setGeometry(QtCore.QRect(770, 200, 120, 40))
        self.danjia_2Edit.setClearButtonEnabled(True)
        self.danjia_2Edit.setValidator(QtGui.QIntValidator())
        self.danjia_2Edit.setObjectName("danjia_2Edit")

        self.jianmianEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.jianmianEdit.setGeometry(QtCore.QRect(770, 250, 120, 40))
        self.jianmianEdit.setClearButtonEnabled(True)
        self.jianmianEdit.setValidator(QtGui.QIntValidator())
        self.jianmianEdit.setObjectName("jianmianEdit")

        self.yuanchadianriqi1Edit = QtWidgets.QDateEdit(CalculatorBox)
        self.yuanchadianriqi1Edit.setGeometry(QtCore.QRect(300, 200, 100, 40))
        self.yuanchadianriqi1Edit.setObjectName("yuanchadianriqi1Edit")
        
        self.yuanchadianriqi2Edit = QtWidgets.QDateEdit(CalculatorBox)
        self.yuanchadianriqi2Edit.setGeometry(QtCore.QRect(420, 200, 100, 40))
        self.yuanchadianriqi2Edit.setObjectName("yuanchadianriqi2Edit")
        
        self.yuanchadiandateEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.yuanchadiandateEdit.setGeometry(QtCore.QRect(560, 200, 100, 40))
        self.yuanchadiandateEdit.setClearButtonEnabled(True)
        self.yuanchadiandateEdit.setValidator(QtGui.QIntValidator())
        self.yuanchadiandateEdit.setObjectName("yuanchadiandateEdit")

        self.yuandalengEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.yuandalengEdit.setGeometry(QtCore.QRect(980, 200, 160, 40))
        self.yuandalengEdit.setClearButtonEnabled(True)
        self.yuandalengEdit.setValidator(QtGui.QIntValidator())
        self.yuandalengEdit.setObjectName("yuandalengEdit")

        self.zuchadianriqi1Edit = QtWidgets.QDateEdit(CalculatorBox)
        self.zuchadianriqi1Edit.setGeometry(QtCore.QRect(300, 250, 100, 40))
        self.zuchadianriqi1Edit.setObjectName("zuchadianriqi1Edit")
        
        self.zuchadianriqi2Edit = QtWidgets.QDateEdit(CalculatorBox)
        self.zuchadianriqi2Edit.setGeometry(QtCore.QRect(420, 250, 100, 40))
        self.zuchadianriqi2Edit.setObjectName("zuchadianriqi2Edit")
        
        self.zuchadiandateEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.zuchadiandateEdit.setGeometry(QtCore.QRect(560, 250, 100, 40))
        self.zuchadiandateEdit.setClearButtonEnabled(True)
        self.zuchadiandateEdit.setValidator(QtGui.QIntValidator())
        self.zuchadiandateEdit.setObjectName("zuchadiandateEdit")

        self.zudalengEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.zudalengEdit.setGeometry(QtCore.QRect(980, 250, 160, 40))
        self.zudalengEdit.setClearButtonEnabled(True)
        self.zudalengEdit.setValidator(QtGui.QIntValidator())
        self.zudalengEdit.setObjectName("zudalengEdit")

        self.zhuanguifeiEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.zhuanguifeiEdit.setGeometry(QtCore.QRect(320, 310, 200, 40))
        self.zhuanguifeiEdit.setClearButtonEnabled(True)
        self.zhuanguifeiEdit.setValidator(QtGui.QIntValidator())
        self.zhuanguifeiEdit.setObjectName("zhuanguifeiEdit")

        self.dabaofeiEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.dabaofeiEdit.setGeometry(QtCore.QRect(720, 310, 200, 40))
        self.dabaofeiEdit.setClearButtonEnabled(True)
        self.dabaofeiEdit.setValidator(QtGui.QIntValidator())
        self.dabaofeiEdit.setObjectName("dabaofeiEdit")

        self.zhafeiEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.zhafeiEdit.setGeometry(QtCore.QRect(320, 360, 200, 40))
        self.zhafeiEdit.setClearButtonEnabled(True)
        self.zhafeiEdit.setValidator(QtGui.QIntValidator())
        self.zhafeiEdit.setObjectName("zhafeiEdit")

        self.diaofeiEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.diaofeiEdit.setGeometry(QtCore.QRect(720, 360, 200, 40))
        self.diaofeiEdit.setClearButtonEnabled(True)
        self.diaofeiEdit.setValidator(QtGui.QIntValidator())
        self.diaofeiEdit.setObjectName("diaofeiEdit")

        self.guobangxiguifeiEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.guobangxiguifeiEdit.setGeometry(QtCore.QRect(320, 410, 200, 40))
        self.guobangxiguifeiEdit.setClearButtonEnabled(True)
        self.guobangxiguifeiEdit.setValidator(QtGui.QIntValidator())
        self.guobangxiguifeiEdit.setObjectName("guobangxiguiEdit")

        self.chuanyunfeiEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.chuanyunfeiEdit.setGeometry(QtCore.QRect(720, 410, 200, 40))
        self.chuanyunfeiEdit.setClearButtonEnabled(True)
        self.chuanyunfeiEdit.setValidator(QtGui.QIntValidator())
        self.chuanyunfeiEdit.setObjectName("chuanyunfeiEdit")

        self.tuochefeiEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.tuochefeiEdit.setGeometry(QtCore.QRect(320, 460, 200, 40))
        self.tuochefeiEdit.setClearButtonEnabled(True)
        self.tuochefeiEdit.setValidator(QtGui.QIntValidator())
        self.tuochefeiEdit.setObjectName("tuochefeiEdit")

        self.weixiufeiEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.weixiufeiEdit.setGeometry(QtCore.QRect(720, 460, 200, 40))
        self.weixiufeiEdit.setClearButtonEnabled(True)
        self.weixiufeiEdit.setValidator(QtGui.QIntValidator())
        self.weixiufeiEdit.setObjectName("weixiufeiEdit")

        self.unitEdit = QtWidgets.QComboBox(CalculatorBox)
        self.unitEdit.setGeometry(QtCore.QRect(320, 510, 200, 40))
        self.unitEdit.addItem("人民幣")
        self.unitEdit.addItem("港幣")
        self.unitEdit.setObjectName("unitEdit")

 
        self.totalEdit = QtWidgets.QLineEdit(CalculatorBox)
        self.totalEdit.setGeometry(QtCore.QRect(720, 510, 200, 40))
        self.totalEdit.setClearButtonEnabled(True)
        self.totalEdit.setValidator(QtGui.QIntValidator())
        self.totalEdit.setObjectName("totalEdit")

        self.okButton = QtWidgets.QPushButton(CalculatorBox)
        self.okButton.setGeometry(QtCore.QRect(400, 580, 120, 40))
        self.okButton.setObjectName("okButton")
        self.okButton.setStyleSheet(
            "QPushButton{color:black;border:1px solid #F3F3F5;border-radius:10px;background:Gray;}"
            "QPushButton:hover{color:black;border:1px solid #F3F3F5;border-radius:10px;background:LightGray;}")

        self.cancelButton = QtWidgets.QPushButton(CalculatorBox)
        self.cancelButton.setGeometry(QtCore.QRect(600, 580, 120, 40))
        self.cancelButton.setObjectName("cancelButton")
        self.cancelButton.setStyleSheet(
            "QPushButton{color:black;border:1px solid #F3F3F5;border-radius:10px;background:Gray;}"
            "QPushButton:hover{color:black;border:1px solid #F3F3F5;border-radius:10px;background:LightGray;}")

        self.msg = QtWidgets.QLabel(CalculatorBox)
        self.msg.setGeometry(QtCore.QRect(11, 10, 641, 40))
        self.msg.setAlignment(QtCore.Qt.AlignCenter)
        self.msg.setObjectName("msg")

        #tab键设置
        self.retranslateUi(CalculatorBox)
        QtCore.QMetaObject.connectSlotsByName(CalculatorBox)
        CalculatorBox.setTabOrder(self.cindexEdit, self.guihaoEdit)
        CalculatorBox.setTabOrder(self.guihaoEdit, self.baolaijianshuEdit)
        CalculatorBox.setTabOrder(self.baolaijianshuEdit, self.tiguiriqiEdit)
        CalculatorBox.setTabOrder(self.tiguiriqiEdit, self.zuguihaoEdit)
        CalculatorBox.setTabOrder(self.zuguihaoEdit, self.zuguiriqi1Edit)
        CalculatorBox.setTabOrder(self.zuguiriqi1Edit, self.zuguiriqi2Edit)
        CalculatorBox.setTabOrder(self.zuguiriqi2Edit, self.zuguidateEdit)
        CalculatorBox.setTabOrder(self.zuguidateEdit, self.danjia_1Edit)
        CalculatorBox.setTabOrder(self.danjia_1Edit, self.zuguifeiEdit)
        CalculatorBox.setTabOrder(self.zuguifeiEdit, self.danjia_2Edit)
        CalculatorBox.setTabOrder(self.danjia_2Edit, self.yuanchadianriqi1Edit)
        CalculatorBox.setTabOrder(self.yuanchadianriqi1Edit, self.yuanchadianriqi2Edit)
        CalculatorBox.setTabOrder(self.yuanchadianriqi2Edit, self.yuandalengEdit)
        CalculatorBox.setTabOrder(self.yuandalengEdit, self.zuchadianriqi1Edit)
        CalculatorBox.setTabOrder(self.zuchadianriqi1Edit, self.zuchadianriqi2Edit)
        CalculatorBox.setTabOrder(self.zuchadianriqi2Edit, self.zudalengEdit)
        CalculatorBox.setTabOrder(self.zudalengEdit, self.zhuanguifeiEdit)
        CalculatorBox.setTabOrder(self.zhuanguifeiEdit, self.zhafeiEdit)
        CalculatorBox.setTabOrder(self.zhafeiEdit, self.diaofeiEdit)
        CalculatorBox.setTabOrder(self.diaofeiEdit, self.guobangxiguifeiEdit)
        CalculatorBox.setTabOrder(self.guobangxiguifeiEdit, self.tuochefeiEdit)
        CalculatorBox.setTabOrder(self.tuochefeiEdit, self.totalEdit)
        CalculatorBox.setTabOrder(self.totalEdit, self.clientEdit)
        CalculatorBox.setTabOrder(self.clientEdit, self.okButton)
        CalculatorBox.setTabOrder(self.okButton, self.cancelButton)

    def retranslateUi(self, CalculatorBox):
        _translate = QtCore.QCoreApplication.translate
        CalculatorBox.setWindowTitle(_translate("CalculatorBox", "訂單結算信息"))
        self.label.setText(_translate("CalculatorBox", "序號"))
        self.label_2.setText(_translate("CalculatorBox", "客戶"))
        self.label_3.setText(_translate("CalculatorBox", "結算日期"))
        self.label_4.setText(_translate("CalculatorBox", "賬單編號"))
        self.label_5.setText(_translate("CalculatorBox", "訂單編號"))
        self.label_6.setText(_translate("CalculatorBox", "櫃號"))
        self.label_7.setText(_translate("CalculatorBox", "報來件數"))
        self.label_8.setText(_translate("CalculatorBox", "提櫃日期"))
        self.label_9.setText(_translate("CalculatorBox", "租櫃號"))
        self.label_10.setText(_translate("CalculatorBox", "租櫃日期(天數)"))
        self.label_11.setText(_translate("CalculatorBox", "——"))
        self.label_12.setText(_translate("CalculatorBox", "共"))
        self.label_13.setText(_translate("CalculatorBox", "天"))
        self.label_14.setText(_translate("CalculatorBox", "单价"))
        self.label_15.setText(_translate("CalculatorBox", "租櫃費"))
        self.label_16.setText(_translate("CalculatorBox", "单价"))
        self.label_17.setText(_translate("CalculatorBox", "原櫃插電日期(天數)"))
        self.label_18.setText(_translate("CalculatorBox", "——"))
        self.label_19.setText(_translate("CalculatorBox", "共"))
        self.label_20.setText(_translate("CalculatorBox", "天"))
        self.label_21.setText(_translate("CalculatorBox", "原櫃打冷"))
        self.label_22.setText(_translate("CalculatorBox", "租櫃插電日期(天數)"))
        self.label_23.setText(_translate("CalculatorBox", "——"))
        self.label_24.setText(_translate("CalculatorBox", "共"))
        self.label_25.setText(_translate("CalculatorBox", "天"))
        self.label_26.setText(_translate("CalculatorBox", "租櫃打冷"))
        self.label_27.setText(_translate("CalculatorBox", "轉櫃費"))
        self.label_28.setText(_translate("CalculatorBox", "閘費"))
        self.label_29.setText(_translate("CalculatorBox", "吊費"))
        self.label_30.setText(_translate("CalculatorBox", "過磅洗櫃費"))
        self.label_31.setText(_translate("CalculatorBox", "出口船運費"))
        self.label_32.setText(_translate("CalculatorBox", "拖車費"))
        self.label_33.setText(_translate("CalculatorBox", "維修費"))
        self.label_34.setText(_translate("CalculatorBox", "計價貨幣"))
        self.label_35.setText(_translate("CalculatorBox", "合計"))
        self.label_36.setText(_translate("CalculatorBox", "減免(天)"))
        self.label_37.setText(_translate("CalculatorBox", "打包費"))

        self.danjia_1Edit.setText("150")
        self.danjia_2Edit.setText("300")
        self.jianmianEdit.setText("3")

        self.okButton.setText(_translate("CalculatorBox", "确定"))
        self.cancelButton.setText(_translate("CalculatorBox", "取消"))
        self.msg.setText(_translate("CalculatorBox", "提示信息"))

        #CalculatorBox.setWindowOpacity(0.98)
        #CalculatorBox.setWindowFlag(QtCore.Qt.FramelessWindowHint)