# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont, QPalette
from PyQt5.QtCore import Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 960)
        MainWindow.setStyleSheet("#MainWindow{background-color: rgb(211, 211, 211)}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.move(20, 20)

        #self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        #self.searchButton.setGeometry(QtCore.QRect(650, 10, 121, 31))
        #self.searchButton.setObjectName("searchButton")

        self.searchEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.searchEdit.setGeometry(QtCore.QRect(10, 10, 350, 35))
        self.searchEdit.setObjectName("searchEdit")
        self.searchEdit.setStyleSheet("border:1px solid gray;width:300px;"
                                    "border-radius:6px;padding:2px 4px;")

        self.searchBox = QtWidgets.QComboBox(self.centralwidget)
        self.searchBox.setGeometry(QtCore.QRect(360, 10, 90, 35))
        self.searchBox.setWhatsThis("")
        self.searchBox.setObjectName("searchBox")
        self.searchBox.addItem("")
        self.searchBox.addItem("")
        self.searchBox.addItem("")
        self.searchBox.addItem("")
        self.searchBox.setStyleSheet("border:1px solid gray;width:300px;border-radius:6px;padding:2px 4px;")

        self.searchBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.searchBox_2.setGeometry(QtCore.QRect(460, 10, 90, 35))
        self.searchBox_2.setWhatsThis("")
        self.searchBox_2.setObjectName("searchBox_2")
        self.searchBox_2.addItem("")
        self.searchBox_2.addItem("")
        self.searchBox_2.addItem("")
        self.searchBox_2.addItem("")
        self.searchBox_2.setStyleSheet("border:1px solid gray;width:300px;border-radius:6px;padding:2px 4px;")

        self.searchDate_1 = QtWidgets.QDateEdit(self.centralwidget)
        self.searchDate_1.setGeometry(QtCore.QRect(560, 10, 140, 35))
        self.searchDate_1.setObjectName("searchDate1")
        self.searchDate_1.setDate(QtCore.QDate.currentDate())
        self.searchDate_1.setStyleSheet("border:1px solid gray;width:300px;border-radius:6px;padding:2px 4px;")
        self.label_range = QtWidgets.QLabel(self.centralwidget)
        self.label_range.setGeometry(QtCore.QRect(705, 10, 15, 35))
        self.searchDate_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.searchDate_2.setGeometry(QtCore.QRect(725, 10, 140, 35))
        self.searchDate_2.setObjectName("searchDate2")
        self.searchDate_2.setDate(QtCore.QDate.currentDate())
        self.searchDate_2.setStyleSheet("border:1px solid gray;width:300px;border-radius:6px;padding:2px 4px;")

        #self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        #self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 860, 840))
        #self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        #self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        #self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        #self.verticalLayout.setObjectName("verticalLayout")

        #self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        #self.horizontalLayoutWidget.setGeometry(QtCore.QRect(880, 20, 900, 870))
        #self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        #self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        #self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        #self.horizontalLayout.setObjectName("horizontalLayout")

        #预览
        self.studentTable = QtWidgets.QTreeWidget(self.centralwidget)
        self.studentTable.setGeometry(QtCore.QRect(10, 50, 1780, 480))
        self.studentTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.studentTable.setObjectName("studentTable")
        self.studentTable.header().setVisible(True)
        self.studentTable.header().setSortIndicatorShown(True)

        #self.verticalLayout.addWidget(self.studentTable)
        #self.verticalLayout.addStretch()

        #结算
        self.calcuTable = QtWidgets.QTreeWidget(self.centralwidget)
        self.calcuTable.setGeometry(QtCore.QRect(10, 580, 1780, 320))
        self.calcuTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.calcuTable.setObjectName("calcuTable")
        self.calcuTable.header().setVisible(True)
        self.calcuTable.header().setSortIndicatorShown(True)

        #self.verticalLayout.addWidget(self.calcuTable)
        #self.horizontalLayout.addLayout(self.verticalLayout)

        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 580, 1780, 320))
        self.groupBox.setStyleSheet("#groupBox{background-color:rgb(250, 250, 250);border:1px solid gray;width:300px;"
                                    "border-radius:10px;padding:2px 4px;}")
        self.groupBox.setObjectName("groupBox")

        #self.horizontalLayout.addWidget(self.groupBox)
        #self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        #self.scrollArea.setWidget(self.groupBox)

        ####2020.01.11
        self.zuohuoTable = QtWidgets.QTreeWidget(self.centralwidget)
        self.zuohuoTable.setGeometry(QtCore.QRect(10, 580, 1780, 320))
        self.zuohuoTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.zuohuoTable.setObjectName("zuohuoTable")
        self.zuohuoTable.header().setVisible(True)
        self.zuohuoTable.header().setSortIndicatorShown(True)

        self.tuozhongTable = QtWidgets.QTreeWidget(self.centralwidget)
        self.tuozhongTable.setGeometry(QtCore.QRect(10, 580, 1780, 320))
        self.tuozhongTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tuozhongTable.setObjectName("tuozhongTable")
        self.tuozhongTable.header().setVisible(True)
        self.tuozhongTable.header().setSortIndicatorShown(True)

        ####2020.01.10
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 580, 1780, 320))
        self.stackedWidget.addWidget(self.groupBox)
        self.stackedWidget.addWidget(self.zuohuoTable)
        self.stackedWidget.addWidget(self.tuozhongTable)

        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 80, 40))
        self.label.setAlignment(QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(240, 20, 80, 40))
        self.label_2.setAlignment(QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(480, 20, 80, 40))
        self.label_3.setAlignment(QtCore.Qt.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(720, 20, 80, 40))
        self.label_4.setAlignment(QtCore.Qt.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(920, 20, 80, 40))
        self.label_5.setAlignment(QtCore.Qt.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(1240, 20, 80, 40))
        self.label_6.setAlignment(QtCore.Qt.AlignLeft)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(1480, 20, 80, 40))
        self.label_7.setAlignment(QtCore.Qt.AlignLeft)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 80, 40))
        self.label_8.setAlignment(QtCore.Qt.AlignLeft)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(240, 70, 80, 40))
        self.label_9.setAlignment(QtCore.Qt.AlignLeft)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(480, 70, 80, 40))
        self.label_10.setAlignment(QtCore.Qt.AlignLeft)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(720, 70, 80, 40))
        self.label_11.setAlignment(QtCore.Qt.AlignLeft)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(920, 70, 80, 40))
        self.label_12.setAlignment(QtCore.Qt.AlignLeft)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(1240, 70, 80, 40))
        self.label_13.setAlignment(QtCore.Qt.AlignLeft)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(1480, 70, 80, 40))
        self.label_14.setAlignment(QtCore.Qt.AlignLeft)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(10, 120, 80, 40))
        self.label_15.setAlignment(QtCore.Qt.AlignLeft)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 170, 80, 40))
        self.label_16.setAlignment(QtCore.Qt.AlignLeft)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(10, 220, 80, 40))
        self.label_17.setAlignment(QtCore.Qt.AlignLeft)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(10, 270, 80, 40))
        self.label_18.setAlignment(QtCore.Qt.AlignLeft)
        self.label_18.setObjectName("label_18")


        self.clientLabel = QtWidgets.QLabel(self.groupBox)
        self.clientLabel.setGeometry(QtCore.QRect(110, 20, 120, 40))
        self.clientLabel.setText("")
        self.clientLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.clientLabel.setObjectName("clientLabel")

        self.dateLabel = QtWidgets.QLabel(self.groupBox)
        self.dateLabel.setGeometry(QtCore.QRect(350, 20, 120, 40))
        self.dateLabel.setText("")
        self.dateLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.dateLabel.setObjectName("dateLabel")

        self.huomingLabel = QtWidgets.QLabel(self.groupBox)
        self.huomingLabel.setGeometry(QtCore.QRect(590, 20, 120, 40))
        self.huomingLabel.setText("")
        self.huomingLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.huomingLabel.setObjectName("huomingLabel")

        self.baolaijianshuLabel = QtWidgets.QLabel(self.groupBox)
        self.baolaijianshuLabel.setGeometry(QtCore.QRect(830, 20, 90, 40))
        self.baolaijianshuLabel.setText("")
        self.baolaijianshuLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.baolaijianshuLabel.setObjectName("baolaijianshuLabel")

        self.yuanguihaoLabel = QtWidgets.QLabel(self.groupBox)
        self.yuanguihaoLabel.setGeometry(QtCore.QRect(1000, 20, 200, 40))
        self.yuanguihaoLabel.setText("")
        self.yuanguihaoLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.yuanguihaoLabel.setObjectName("yuanguihaoLabel")

        self.zhongweiLabel = QtWidgets.QLabel(self.groupBox)
        self.zhongweiLabel.setGeometry(QtCore.QRect(1350, 20, 120, 40))
        self.zhongweiLabel.setText("")
        self.zhongweiLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.zhongweiLabel.setObjectName("zhongweiLabel")

        self.jiweiLabel = QtWidgets.QLabel(self.groupBox)
        self.jiweiLabel.setGeometry(QtCore.QRect(1590, 20, 120, 40))
        self.jiweiLabel.setText("")
        self.jiweiLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.jiweiLabel.setObjectName("jiweiLabel")

        self.fangxiangriqiLabel = QtWidgets.QLabel(self.groupBox)
        self.fangxiangriqiLabel.setGeometry(QtCore.QRect(110, 70, 120, 40))
        self.fangxiangriqiLabel.setText("")
        self.fangxiangriqiLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.fangxiangriqiLabel.setObjectName("fangxiangriqiLabel")
 
        self.zhongweiriqiLabel = QtWidgets.QLabel(self.groupBox)
        self.zhongweiriqiLabel.setGeometry(QtCore.QRect(350, 70, 120, 40))
        self.zhongweiriqiLabel.setText("")
        self.zhongweiriqiLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.zhongweiriqiLabel.setObjectName("zhongweiriqiLabel")

        self.bangzhongLabel = QtWidgets.QLabel(self.groupBox)
        self.bangzhongLabel.setGeometry(QtCore.QRect(590, 70, 120, 40))
        self.bangzhongLabel.setText("")
        self.bangzhongLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.bangzhongLabel.setObjectName("bangzhongLabel")

        self.shishoujianshuLabel = QtWidgets.QLabel(self.groupBox)
        self.shishoujianshuLabel.setGeometry(QtCore.QRect(830, 70, 90, 40))
        self.shishoujianshuLabel.setText("")
        self.shishoujianshuLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.shishoujianshuLabel.setObjectName("shishoujianshuLabel")

        self.baozhuangLabel = QtWidgets.QLabel(self.groupBox)
        self.baozhuangLabel.setGeometry(QtCore.QRect(1000, 70, 200, 40))
        self.baozhuangLabel.setText("")
        self.baozhuangLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.baozhuangLabel.setObjectName("baozhuangLabel")

        self.jiedanriqiLabel = QtWidgets.QLabel(self.groupBox)
        self.jiedanriqiLabel.setGeometry(QtCore.QRect(1350, 70, 120, 40))
        self.jiedanriqiLabel.setText("")
        self.jiedanriqiLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.jiedanriqiLabel.setObjectName("jiedanriqiLabel")

        self.jiesuanzhuangtaiLabel = QtWidgets.QLabel(self.groupBox)
        self.jiesuanzhuangtaiLabel.setGeometry(QtCore.QRect(1590, 70, 120, 40))
        self.jiesuanzhuangtaiLabel.setText("")
        self.jiesuanzhuangtaiLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.jiesuanzhuangtaiLabel.setObjectName("jiesuanzhuangtaiLabel")

        self.notes1Label = QtWidgets.QLabel(self.groupBox)
        self.notes1Label.setGeometry(QtCore.QRect(110, 120, 700, 40))
        self.notes1Label.setText("")
        self.notes1Label.setAlignment(QtCore.Qt.AlignLeft)
        self.notes1Label.setWordWrap(True)
        self.notes1Label.setObjectName("notes1Label")
        self.notes2Label = QtWidgets.QLabel(self.groupBox)
        self.notes2Label.setGeometry(QtCore.QRect(110, 170, 700, 40))
        self.notes2Label.setText("")
        self.notes2Label.setAlignment(QtCore.Qt.AlignLeft)
        self.notes2Label.setWordWrap(True)
        self.notes2Label.setObjectName("notes2Label")
        self.notes3Label = QtWidgets.QLabel(self.groupBox)
        self.notes3Label.setGeometry(QtCore.QRect(110, 220, 700, 40))
        self.notes3Label.setText("")
        self.notes3Label.setAlignment(QtCore.Qt.AlignLeft)
        self.notes3Label.setWordWrap(True)
        self.notes3Label.setObjectName("notes3Label")
        self.notes4Label = QtWidgets.QLabel(self.groupBox)
        self.notes4Label.setGeometry(QtCore.QRect(110, 270, 700, 40))
        self.notes4Label.setText("")
        self.notes4Label.setAlignment(QtCore.Qt.AlignLeft)
        self.notes4Label.setWordWrap(True)
        self.notes4Label.setObjectName("notes4Label")
        #self.notes4Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)

        self.newButton = QtWidgets.QPushButton(self.centralwidget)
        self.newButton.setGeometry(QtCore.QRect(880, 10, 100, 35))
        self.newButton.setObjectName("newButton")
        self.newButton.setStyleSheet(
            "QPushButton{color:black;border:1px solid #F3F3F5;border-radius:10px;background:White;}"
            "QPushButton:hover{color:black;border:1px solid #F3F3F5;border-radius:10px;background:Gray;}")

        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setGeometry(QtCore.QRect(990, 10, 100, 35))
        self.editButton.setObjectName("editButton")
        self.editButton.setStyleSheet(
            "QPushButton{color:black;border:1px solid #F3F3F5;border-radius:10px;background:White;}"
            "QPushButton:hover{color:black;border:1px solid #F3F3F5;border-radius:10px;background:Gray;}")

        #self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        #self.deleteButton.setGeometry(QtCore.QRect(1100, 10, 100, 35))
        #self.deleteButton.setObjectName("deleteButton")
        #self.deleteButton.setStyleSheet(
        #    "QPushButton{color:black;border:1px solid #F3F3F5;border-radius:10px;background:White;}"
        #    "QPushButton:hover{color:black;border:1px solid #F3F3F5;border-radius:10px;background:Gray;}")


        self.dateComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.dateComboBox.setGeometry(QtCore.QRect(10, 540, 100, 35))
        self.dateComboBox.setWhatsThis("")
        self.dateComboBox.setObjectName("dateComboBox")
        self.dateComboBox.addItem("")
        self.dateComboBox.addItem("")
        self.dateComboBox.setStyleSheet("border:1px solid gray;width:300px;border-radius:6px;padding:2px 4px;")

        self.searchDate_3 = QtWidgets.QDateEdit(self.centralwidget)
        self.searchDate_3.setGeometry(QtCore.QRect(130, 540, 120, 35))
        self.searchDate_3.setObjectName("searchDate3")
        self.searchDate_3.setDate(QtCore.QDate.currentDate())
        self.searchDate_3.setStyleSheet("border:1px solid gray;width:300px;border-radius:6px;padding:2px 4px;")

        # 做货button
        self.zuohuosettleButton = QtWidgets.QPushButton(self.centralwidget)
        self.zuohuosettleButton.setGeometry(QtCore.QRect(530, 540, 100, 35))
        self.zuohuosettleButton.setObjectName("zuohuosettleButton")
        self.zuohuosettleButton.setStyleSheet(
            "QPushButton{color:black;border:1px solid #F3F3F5;border-radius:10px;background:White;}"
            "QPushButton:hover{color:black;border:1px solid #F3F3F5;border-radius:10px;background:Gray;}")
        # 拖重button
        self.tuozhongsettleButton = QtWidgets.QPushButton(self.centralwidget)
        self.tuozhongsettleButton.setGeometry(QtCore.QRect(410, 540, 100, 35))
        self.tuozhongsettleButton.setObjectName("tuozhongsettleButton")
        self.tuozhongsettleButton.setStyleSheet(
            "QPushButton{color:black;border:1px solid #F3F3F5;border-radius:10px;background:White;}"
            "QPushButton:hover{color:black;border:1px solid #F3F3F5;border-radius:10px;background:Gray;}")

        self.pageComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.pageComboBox.setGeometry(QtCore.QRect(270, 540, 120, 35))
        self.pageComboBox.addItem("報單信息")
        self.pageComboBox.addItem("做貨工作單")
        self.pageComboBox.addItem("拖重工作單")
        self.pageComboBox.activated[int].connect(self.stackedWidget.setCurrentIndex)
        self.pageComboBox.setStyleSheet("border:1px solid gray;width:300px;border-radius:6px;padding:2px 4px;")

        #self.settleButton = QtWidgets.QPushButton(self.centralwidget)
        #self.settleButton.setGeometry(QtCore.QRect(1550, 10, 100, 35))
        #self.settleButton.setObjectName("settleButton")
        #self.settleButton.setStyleSheet(
        #    "QPushButton{color:black;border:1px solid #F3F3F5;border-radius:10px;background:White;}"
        #    "QPushButton:hover{color:black;border:1px solid #F3F3F5;border-radius:10px;background:Gray;}")

        #self.printButton = QtWidgets.QPushButton(self.centralwidget)
        #self.printButton.setGeometry(QtCore.QRect(1660, 10, 100, 35))
        #self.printButton.setObjectName("printButton")
        #self.printButton.setStyleSheet(
        #    "QPushButton{color:black;border:1px solid #F3F3F5;border-radius:10px;background:White;}"
        #    "QPushButton:hover{color:black;border:1px solid #F3F3F5;border-radius:10px;background:Gray;}")
        #删除做货/拖重/结算单
        self.deleteButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton_2.setGeometry(QtCore.QRect(770, 540, 100, 35))
        self.deleteButton_2.setObjectName("deleteButton_2")
        self.deleteButton_2.setStyleSheet("QPushButton{color:black;border:1px solid #F3F3F5;border-radius:10px;background:White;}"
            "QPushButton:hover{color:black;border:1px solid #F3F3F5;border-radius:10px;background:Gray;}")
        self.deleteButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton_3.setGeometry(QtCore.QRect(890, 540, 100, 35))
        self.deleteButton_3.setObjectName("deleteButton_3")
        self.deleteButton_3.setStyleSheet(
            "QPushButton{color:black;border:1px solid #F3F3F5;border-radius:10px;background:White;}"
            "QPushButton:hover{color:black;border:1px solid #F3F3F5;border-radius:10px;background:Gray;}")

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setToolTip("")
        self.statusbar.setStatusTip("")
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setCentralWidget(self.centralwidget)
        MainWindow.setStatusBar(self.statusbar)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1010, 26))
        self.menubar.setObjectName("menubar")
        self.sysMenu = QtWidgets.QMenu(self.menubar)
        self.sysMenu.setObjectName("sysMenu")
        self.exportMenu = QtWidgets.QMenu(self.sysMenu)
        self.exportMenu.setToolTip("")
        self.exportMenu.setObjectName("exportMenu")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.helpMenu = QtWidgets.QMenu(self.menubar)
        self.helpMenu.setObjectName("helpMenu")
        self.viewMenu = QtWidgets.QMenu(self.menubar)
        self.viewMenu.setObjectName("viewMenu")
        MainWindow.setMenuBar(self.menubar)

        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.exportSelected = QtWidgets.QAction(MainWindow)
        self.exportSelected.setObjectName("exportSelected")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionDelete_2 = QtWidgets.QAction(MainWindow)
        self.actionDelete_2.setObjectName("actionDelete_2")
        self.actionDelete_3 = QtWidgets.QAction(MainWindow)
        self.actionDelete_3.setObjectName("actionDelete_3")
        self.actiontuozhongDelete = QtWidgets.QAction(MainWindow)
        self.actiontuozhongDelete.setObjectName("actiontuozhongDelete")
        self.actionzuohuoDelete = QtWidgets.QAction(MainWindow)
        self.actionzuohuoDelete.setObjectName("actionzuohuoDelete")

        self.actionSettle = QtWidgets.QAction(MainWindow)
        self.actionSettle.setObjectName("actionSettle")

        #做货action
        self.actionzuohuoSettle = QtWidgets.QAction(MainWindow)
        self.actionzuohuoSettle.setObjectName("actionzuohuoSettle")
        ####
        #拖重action
        self.actiontuozhongSettle = QtWidgets.QAction(MainWindow)
        self.actiontuozhongSettle.setObjectName("actiontuozhongSettle")


        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        #self.actionPrint = QtWidgets.QAction(MainWindow)
        #self.actionPrint.setObjectName("actionPrint")
        self.actionSelected = QtWidgets.QAction(MainWindow)
        self.actionSelected.setObjectName("actionSelected")
        self.actionResult = QtWidgets.QAction(MainWindow)
        self.actionResult.setObjectName("actionResult")
        self.actionAll = QtWidgets.QAction(MainWindow)
        self.actionAll.setObjectName("actionAll")
        self.actionUrl = QtWidgets.QAction(MainWindow)
        self.actionUrl.setObjectName("actionUrl")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.exportAll = QtWidgets.QAction(MainWindow)
        self.exportAll.setObjectName("exportAll")
        self.exportMenu.addAction(self.exportSelected)
        self.exportMenu.addAction(self.exportAll)
        self.sysMenu.addAction(self.actionSave)
        self.sysMenu.addAction(self.actionSaveAs)
        self.sysMenu.addSeparator()
        self.sysMenu.addAction(self.exportMenu.menuAction())
        self.sysMenu.addSeparator()
        self.sysMenu.addAction(self.actionExit)
        self.menu.addAction(self.actionAdd)
        self.menu.addSeparator()
        self.menu.addAction(self.actionEdit)
        self.menu.addAction(self.actionzuohuoSettle)
        self.menu.addAction(self.actionzuohuoDelete)
        self.menu.addAction(self.actiontuozhongSettle)
        self.menu.addAction(self.actiontuozhongDelete)

        self.helpMenu.addAction(self.actionUrl)
        self.helpMenu.addAction(self.actionAbout)
        self.menubar.addAction(self.sysMenu.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.viewMenu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "辉腾報單管理系统"))
        self.searchBox.setStatusTip(_translate("MainWindow", "快速检索项"))
        self.searchBox.setItemText(0, _translate("MainWindow", "序號"))
        self.searchBox.setItemText(1, _translate("MainWindow", "客戶"))
        self.searchBox.setItemText(2, _translate("MainWindow", "櫃號"))
        self.searchBox.setItemText(3, _translate("MainWindow", "結算狀態"))

        self.searchBox_2.setStatusTip(_translate("MainWindow", "時間檢索項"))
        self.searchBox_2.setItemText(0, _translate("MainWindow", "不限日期"))
        self.searchBox_2.setItemText(1, _translate("MainWindow", "重尾"))
        self.searchBox_2.setItemText(2, _translate("MainWindow", "拖重日期"))
        self.searchBox_2.setItemText(3, _translate("MainWindow", "結單日期"))

        self.dateComboBox.setStatusTip(_translate("MainWindow", "日期檢索"))
        self.dateComboBox.setItemText(0, _translate("MainWindow", "不限日期"))
        self.dateComboBox.setItemText(1, _translate("MainWindow", "日期檢索"))

        self.studentTable.setStatusTip(_translate("MainWindow", "双击修改信息"))
        self.studentTable.setSortingEnabled(True)
        #報單信息
        self.studentTable.headerItem().setText(0, _translate("MainWindow", "序號"))
        self.studentTable.headerItem().setText(1, _translate("MainWindow", "客戶"))
        self.studentTable.headerItem().setText(2, _translate("MainWindow", "收單日期"))
        self.studentTable.headerItem().setText(3, _translate("MainWindow", "結單日期"))
        self.studentTable.headerItem().setText(4, _translate("MainWindow", "結算狀態"))
        self.studentTable.headerItem().setText(5, _translate("MainWindow", "原櫃號"))
        self.studentTable.headerItem().setText(6, _translate("MainWindow", "重尾"))
        self.studentTable.headerItem().setText(7, _translate("MainWindow", "吉尾"))
        self.studentTable.headerItem().setText(8, _translate("MainWindow", "放箱日期"))
        self.studentTable.headerItem().setText(9, _translate("MainWindow", "拖重日期"))
        self.studentTable.headerItem().setText(10, _translate("MainWindow", "過櫃備注"))
        self.studentTable.headerItem().setText(11, _translate("MainWindow", "出貨備注"))
        self.studentTable.headerItem().setText(12, _translate("MainWindow", "訂單備注"))
        self.studentTable.headerItem().setText(13, _translate("MainWindow", "拖重備注"))
        self.studentTable.headerItem().setText(14, _translate("MainWindow", "付貨人"))
        self.studentTable.headerItem().setText(15, _translate("MainWindow", "貨名"))
        self.studentTable.headerItem().setText(16, _translate("MainWindow", "客戶净重(KG)"))
        self.studentTable.headerItem().setText(17, _translate("MainWindow", "客戶毛重(KG)"))
        self.studentTable.headerItem().setText(18, _translate("MainWindow", "報來件數"))
        self.studentTable.headerItem().setText(19, _translate("MainWindow", "件重"))  ###净重/報來件數
        self.studentTable.headerItem().setText(20, _translate("MainWindow", "實收磅重"))
        self.studentTable.headerItem().setText(21, _translate("MainWindow", "實收件數"))
        self.studentTable.headerItem().setText(22, _translate("MainWindow", "包裝"))

        #過櫃記錄
        self.studentTable.headerItem().setText(23, _translate("MainWindow", "過櫃日期1"))
        self.studentTable.headerItem().setText(24, _translate("MainWindow", "過櫃櫃號1"))
        self.studentTable.headerItem().setText(25, _translate("MainWindow", "過櫃日期2"))
        self.studentTable.headerItem().setText(26, _translate("MainWindow", "過櫃櫃號2"))
        self.studentTable.headerItem().setText(27, _translate("MainWindow", "過櫃日期3"))
        self.studentTable.headerItem().setText(28, _translate("MainWindow", "過櫃櫃號3"))
        self.studentTable.headerItem().setText(29, _translate("MainWindow", "過櫃日期4"))
        self.studentTable.headerItem().setText(30, _translate("MainWindow", "出口櫃號"))
        #出貨記錄
        self.studentTable.headerItem().setText(31, _translate("MainWindow", "出貨日期1"))
        self.studentTable.headerItem().setText(32, _translate("MainWindow", "出貨件數1"))
        self.studentTable.headerItem().setText(33, _translate("MainWindow", "出貨櫃號1"))
        self.studentTable.headerItem().setText(34, _translate("MainWindow", "出貨日期2"))
        self.studentTable.headerItem().setText(35, _translate("MainWindow", "出貨件數2"))
        self.studentTable.headerItem().setText(36, _translate("MainWindow", "出貨櫃號2"))
        self.studentTable.headerItem().setText(37, _translate("MainWindow", "出貨日期3"))
        self.studentTable.headerItem().setText(38, _translate("MainWindow", "出貨件數3"))
        self.studentTable.headerItem().setText(39, _translate("MainWindow", "出貨櫃號3"))
        self.studentTable.headerItem().setText(40, _translate("MainWindow", "出貨日期4"))
        self.studentTable.headerItem().setText(41, _translate("MainWindow", "出貨件數4"))
        self.studentTable.headerItem().setText(42, _translate("MainWindow", "出貨櫃號4"))
        self.studentTable.headerItem().setText(43, _translate("MainWindow", "出貨日期5"))
        self.studentTable.headerItem().setText(44, _translate("MainWindow", "出貨件數5"))
        self.studentTable.headerItem().setText(45, _translate("MainWindow", "出貨櫃號5"))

        #self.studentTable.resizeColumnToContents(0)

        #做货记录
        self.zuohuoTable.setStatusTip(_translate("MainWindow", "双击修改信息"))
        self.zuohuoTable.setSortingEnabled(True)
        self.zuohuoTable.headerItem().setText(0, _translate("MainWindow", "序"))
        self.zuohuoTable.headerItem().setText(1, _translate("MainWindow", "日期"))
        self.zuohuoTable.headerItem().setText(2, _translate("MainWindow", "原櫃號"))
        self.zuohuoTable.headerItem().setText(3, _translate("MainWindow", "件數"))
        self.zuohuoTable.headerItem().setText(4, _translate("MainWindow", "淨重"))
        self.zuohuoTable.headerItem().setText(5, _translate("MainWindow", "毛重"))
        self.zuohuoTable.headerItem().setText(6, _translate("MainWindow", "貨名"))
        self.zuohuoTable.headerItem().setText(7, _translate("MainWindow", "實收件數"))
        self.zuohuoTable.headerItem().setText(8, _translate("MainWindow", "轉櫃號"))
        self.zuohuoTable.headerItem().setText(9, _translate("MainWindow", "包裝"))
        self.zuohuoTable.headerItem().setText(10, _translate("MainWindow", "備註"))

        #拖重記錄
        self.tuozhongTable.setStatusTip(_translate("MainWindow", "双击修改信息"))
        self.tuozhongTable.setSortingEnabled(True)
        self.tuozhongTable.headerItem().setText(0, _translate("MainWindow", "序"))
        self.tuozhongTable.headerItem().setText(1, _translate("MainWindow", "日期"))
        self.tuozhongTable.headerItem().setText(2, _translate("MainWindow", "櫃號"))
        self.tuozhongTable.headerItem().setText(3, _translate("MainWindow", "重尾"))
        self.tuozhongTable.headerItem().setText(4, _translate("MainWindow", "吉尾"))
        self.tuozhongTable.headerItem().setText(5, _translate("MainWindow", "件數"))
        self.tuozhongTable.headerItem().setText(6, _translate("MainWindow", "淨重"))
        self.tuozhongTable.headerItem().setText(7, _translate("MainWindow", "毛重"))
        self.tuozhongTable.headerItem().setText(8, _translate("MainWindow", "貨名"))
        self.tuozhongTable.headerItem().setText(9, _translate("MainWindow", "磅單重量"))
        self.tuozhongTable.headerItem().setText(10, _translate("MainWindow", "備註"))

        #详细信息展示
        #self.groupBox.setTitle(_translate("MainWindow", "報單信息"))
        self.label.setText(_translate("MainWindow", "客戶"))
        self.label_2.setText(_translate("MainWindow", "收單日期"))
        self.label_3.setText(_translate("MainWindow", "貨名"))
        self.label_4.setText(_translate("MainWindow", "報來件數"))
        self.label_5.setText(_translate("MainWindow", "原櫃號"))
        self.label_6.setText(_translate("MainWindow", "重尾"))
        self.label_7.setText(_translate("MainWindow", "吉尾"))
        self.label_8.setText(_translate("MainWindow", "放箱日期"))
        self.label_9.setText(_translate("MainWindow", "拖重日期"))
        self.label_10.setText(_translate("MainWindow", "實收磅重"))
        self.label_11.setText(_translate("MainWindow", "實收件數"))
        self.label_12.setText(_translate("MainWindow", "包裝"))
        self.label_13.setText(_translate("MainWindow", "結單日期"))
        self.label_14.setText(_translate("MainWindow", "結算狀態"))
        self.label_15.setText(_translate("MainWindow", "拖重備注"))
        self.label_16.setText(_translate("MainWindow", "過櫃備注"))
        self.label_17.setText(_translate("MainWindow", "出貨備注"))
        self.label_18.setText(_translate("MainWindow", "訂單備注"))
        
        self.label_range.setText(_translate("MainWindow", "——"))
		
        self.editButton.setStatusTip(_translate("MainWindow", "修改当前报单信息"))
        self.editButton.setText(_translate("MainWindow", "修改..."))
        #self.deleteButton.setStatusTip(_translate("MainWindow", "删除档案, 一旦删除数据不可恢复"))
        #self.deleteButton.setText(_translate("MainWindow", "删除"))

        self.deleteButton_2.setStatusTip(_translate("MainWindow", "删除档案, 一旦删除数据不可恢复"))
        self.deleteButton_2.setText(_translate("MainWindow", "删除做貨單"))

        self.deleteButton_3.setStatusTip(_translate("MainWindow", "删除档案, 一旦删除数据不可恢复"))
        self.deleteButton_3.setText(_translate("MainWindow", "删除拖重單"))
        #self.settleButton.setStatusTip(_translate("MainWindow", "結算报单"))
        #self.settleButton.setText(_translate("MainWindow", "結算"))
        ###做貨button
        self.zuohuosettleButton.setStatusTip(_translate("MainWindow", "生成做貨記錄"))
        self.zuohuosettleButton.setText(_translate("MainWindow", "生成做貨單"))
        #拖重button
        self.tuozhongsettleButton.setStatusTip(_translate("MainWindow", "生成拖重記錄"))
        self.tuozhongsettleButton.setText(_translate("MainWindow", "生成拖重單"))

        self.newButton.setStatusTip(_translate("MainWindow", "新建入单"))
        self.newButton.setText(_translate("MainWindow", "新建報單..."))

        #self.printButton.setStatusTip(_translate("MainWindow", "打印結算表單"))
        #self.printButton.setText(_translate("MainWindow", "打印結算表單"))
        self.sysMenu.setTitle(_translate("MainWindow", "系统"))
        self.exportMenu.setStatusTip(_translate("MainWindow", "转换数据为Excel格式"))
        self.exportMenu.setTitle(_translate("MainWindow", "導出至Excel"))
        self.menu.setTitle(_translate("MainWindow", "報單"))
        self.helpMenu.setTitle(_translate("MainWindow", "帮助"))
        self.viewMenu.setTitle(_translate("MainWindow", "视图"))
        self.action.setText(_translate("MainWindow", "\\"))
        self.actionSave.setText(_translate("MainWindow", "保存報單"))
        self.actionSave.setToolTip(_translate("MainWindow", "保存報單"))
        self.actionSave.setStatusTip(_translate("MainWindow", "保存報單(系统退出时会自动保存)"))
        self.actionSaveAs.setText(_translate("MainWindow", "另存報單..."))
        self.actionSaveAs.setStatusTip(_translate("MainWindow", "保存一份副本"))
        self.exportSelected.setText(_translate("MainWindow", "选中報單..."))
        self.exportSelected.setStatusTip(_translate("MainWindow", "導出當前列表中的報單"))
        self.actionEdit.setText(_translate("MainWindow", "修改"))
        self.actionEdit.setStatusTip(_translate("MainWindow", "修改當前報單信息"))
        self.actionDelete.setText(_translate("MainWindow", "删除"))
        self.actionDelete.setStatusTip(_translate("MainWindow", "删除報單, 一旦删除数据不可恢復"))
        self.actionDelete_2.setText(_translate("MainWindow", "删除做貨單"))
        self.actionDelete_2.setStatusTip(_translate("MainWindow", "刪除做貨單，一旦删除数据不可恢复"))
        self.actionDelete_3.setText(_translate("MainWindow", "删除拖重單"))
        self.actionDelete_3.setStatusTip(_translate("MainWindow", "刪除拖重單，一旦删除数据不可恢复"))
        self.actiontuozhongSettle.setText(_translate("MainWindow", "生成拖重單"))
        self.actiontuozhongSettle.setStatusTip(_translate("MainWindow", "生成拖重單"))
        self.actiontuozhongDelete.setText(_translate("MainWindow", "删除拖重單"))
        self.actiontuozhongDelete.setStatusTip(_translate("MainWindow", "删除拖重單, 一旦删除数据不可恢復"))
        self.actionzuohuoSettle.setText(_translate("MainWindow", "生成做貨單"))
        self.actionzuohuoSettle.setStatusTip(_translate("MainWindow", "生成做貨單"))
        self.actionzuohuoDelete.setText(_translate("MainWindow", "删除做貨單"))
        self.actionzuohuoDelete.setStatusTip(_translate("MainWindow", "删除做貨單, 一旦删除数据不可恢復"))

        self.actionSettle.setText(_translate("MainWindow", "結算"))
        self.actionSettle.setStatusTip(_translate("MainWindow", "結算報單"))
        self.actionAdd.setText(_translate("MainWindow", "新建入单..."))
        self.actionAdd.setStatusTip(_translate("MainWindow", "新建入单"))
        #self.actionPrint.setText(_translate("MainWindow", "打印結算表單..."))
        #self.actionPrint.setStatusTip(_translate("MainWindow", "打印結算表單"))
        self.actionSelected.setText(_translate("MainWindow", "选中報單..."))
        self.actionResult.setText(_translate("MainWindow", "报表内報單..."))
        self.actionAll.setText(_translate("MainWindow", "所有報單..."))
        self.actionUrl.setText(_translate("MainWindow", "訪問網站"))
        self.actionUrl.setStatusTip(_translate("MainWindow", "訪問頁面"))
        self.actionAbout.setText(_translate("MainWindow", "關於"))
        self.actionAbout.setStatusTip(_translate("MainWindow", "關於系統"))
        self.actionExit.setText(_translate("MainWindow", "退出系统"))
        self.actionExit.setStatusTip(_translate("MainWindow", "退出管理系统"))
        self.exportAll.setText(_translate("MainWindow", "所有報單..."))
        self.exportAll.setStatusTip(_translate("MainWindow", "导出整个報表"))

        #MainWindow.setWindowOpacity(0.98)
        #MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)