# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'studentBox.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StudentBox_2(object):
    def setupUi(self, StudentBox):
        StudentBox.setObjectName("StudentBox")
        StudentBox.resize(1400, 880)
        StudentBox.setStyleSheet("#StudentBox{background-color: rgb(238, 233, 233)}")
        self.label = QtWidgets.QLabel(StudentBox)
        self.label.setGeometry(QtCore.QRect(50, 50, 80, 30))
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(StudentBox)
        self.label_2.setGeometry(QtCore.QRect(50, 85, 80, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(StudentBox)
        self.label_3.setGeometry(QtCore.QRect(50, 120, 80, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(StudentBox)
        self.label_4.setGeometry(QtCore.QRect(50, 155, 80, 30))
        self.label_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(StudentBox)
        self.label_5.setGeometry(QtCore.QRect(50, 190, 80, 30))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(StudentBox)
        self.label_6.setGeometry(QtCore.QRect(50, 225, 80, 30))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(StudentBox)
        self.label_7.setGeometry(QtCore.QRect(50, 260, 80, 30))
        self.label_7.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(StudentBox)
        self.label_8.setGeometry(QtCore.QRect(50, 295, 80, 30))
        self.label_8.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(StudentBox)
        self.label_9.setGeometry(QtCore.QRect(50, 330, 80, 30))
        self.label_9.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(StudentBox)
        self.label_10.setGeometry(QtCore.QRect(50, 365, 80, 30))
        self.label_10.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(StudentBox)
        self.label_11.setGeometry(QtCore.QRect(50, 400, 80, 30))
        self.label_11.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_11.setStyleSheet("color:red")
        self.label_12 = QtWidgets.QLabel(StudentBox)
        self.label_12.setGeometry(QtCore.QRect(50, 435, 80, 30))
        self.label_12.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_12.setStyleSheet("color:red")
        self.label_13 = QtWidgets.QLabel(StudentBox)
        self.label_13.setGeometry(QtCore.QRect(50, 470, 80, 30))
        self.label_13.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_13.setStyleSheet("color:red")
        self.label_14 = QtWidgets.QLabel(StudentBox)
        self.label_14.setGeometry(QtCore.QRect(50, 505, 80, 30))
        self.label_14.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.label_14.setStyleSheet("color:red")
        self.label_15 = QtWidgets.QLabel(StudentBox)
        self.label_15.setGeometry(QtCore.QRect(50, 610, 80, 30))
        self.label_15.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_15.setStyleSheet("color:red")
        self.label_16 = QtWidgets.QLabel(StudentBox)
        self.label_16.setGeometry(QtCore.QRect(50, 645, 80, 30))
        self.label_16.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_16.setStyleSheet("color:red")
        self.label_17 = QtWidgets.QLabel(StudentBox)
        self.label_17.setGeometry(QtCore.QRect(500, 50, 80, 30))
        self.label_17.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.label_17.setStyleSheet("color:red")
        self.label_18 = QtWidgets.QLabel(StudentBox)
        self.label_18.setGeometry(QtCore.QRect(500, 190, 80, 30))
        self.label_18.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(StudentBox)
        self.label_19.setGeometry(QtCore.QRect(500, 225, 80, 30))
        self.label_19.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(StudentBox)
        self.label_20.setGeometry(QtCore.QRect(500, 260, 80, 30))
        self.label_20.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")		
        self.label_21 = QtWidgets.QLabel(StudentBox)
        self.label_21.setGeometry(QtCore.QRect(500, 295, 80, 30))
        self.label_21.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(StudentBox)
        self.label_22.setGeometry(QtCore.QRect(500, 330, 80, 30))
        self.label_22.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(StudentBox)
        self.label_23.setGeometry(QtCore.QRect(500, 365, 80, 30))
        self.label_23.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(StudentBox)
        self.label_24.setGeometry(QtCore.QRect(500, 400, 80, 30))
        self.label_24.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(StudentBox)
        self.label_25.setGeometry(QtCore.QRect(500, 435, 80, 30))
        self.label_25.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(StudentBox)
        self.label_26.setGeometry(QtCore.QRect(500, 470, 80, 30))
        self.label_26.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(StudentBox)
        self.label_27.setGeometry(QtCore.QRect(500, 505, 80, 30))
        self.label_27.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(StudentBox)
        self.label_28.setGeometry(QtCore.QRect(950, 50, 80, 30))
        self.label_28.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(StudentBox)
        self.label_29.setGeometry(QtCore.QRect(950, 85, 80, 30))
        self.label_29.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(StudentBox)
        self.label_30.setGeometry(QtCore.QRect(950, 120, 80, 30))
        self.label_30.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(StudentBox)
        self.label_31.setGeometry(QtCore.QRect(950, 155, 80, 30))
        self.label_31.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(StudentBox)
        self.label_32.setGeometry(QtCore.QRect(950, 190, 80, 30))
        self.label_32.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(StudentBox)
        self.label_33.setGeometry(QtCore.QRect(950, 225, 80, 30))
        self.label_33.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(StudentBox)
        self.label_34.setGeometry(QtCore.QRect(950, 260, 80, 30))
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(StudentBox)
        self.label_35.setGeometry(QtCore.QRect(950, 295, 80, 30))
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(StudentBox)
        self.label_36.setGeometry(QtCore.QRect(950, 330, 80, 30))
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(StudentBox)
        self.label_37.setGeometry(QtCore.QRect(950, 365, 80, 30))
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(StudentBox)
        self.label_38.setGeometry(QtCore.QRect(950, 400, 80, 30))
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(StudentBox)
        self.label_39.setGeometry(QtCore.QRect(950, 435, 80, 30))
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(StudentBox)
        self.label_40.setGeometry(QtCore.QRect(950, 470, 80, 30))
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(StudentBox)
        self.label_41.setGeometry(QtCore.QRect(950, 505, 80, 30))
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(StudentBox)
        self.label_42.setGeometry(QtCore.QRect(950, 540, 80, 30))
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(StudentBox)
        self.label_43.setGeometry(QtCore.QRect(950, 575, 80, 30))
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.label_43.setStyleSheet("color:red")
        self.label_44 = QtWidgets.QLabel(StudentBox)
        self.label_44.setGeometry(QtCore.QRect(950, 610, 80, 30))
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.label_44.setStyleSheet("color:red")
        self.label_45 = QtWidgets.QLabel(StudentBox)
        self.label_45.setGeometry(QtCore.QRect(100, 715, 80, 30))
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.label_45.setStyleSheet("color:red")
        self.label_46 = QtWidgets.QLabel(StudentBox)
        self.label_46.setGeometry(QtCore.QRect(100, 795, 80, 30))
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.label_46.setStyleSheet("color:red")

        self.indexEdit = QtWidgets.QLineEdit(StudentBox)
        self.indexEdit.setGeometry(QtCore.QRect(160, 55, 201, 30))
        self.indexEdit.setDragEnabled(False)
        self.indexEdit.setClearButtonEnabled(True)
        self.indexEdit.setObjectName("indexEdit")
        self.clientEdit = QtWidgets.QLineEdit(StudentBox)
        self.clientEdit.setGeometry(QtCore.QRect(160, 90, 201, 30))
        self.clientEdit.setClearButtonEnabled(True)
        self.clientEdit.setObjectName("clientEdit")
        self.fuhuoEdit = QtWidgets.QLineEdit(StudentBox)
        self.fuhuoEdit.setGeometry(QtCore.QRect(160, 125, 201, 30))
        self.fuhuoEdit.setClearButtonEnabled(True)
        self.fuhuoEdit.setObjectName("fuhuoEdit")
        self.dateEdit = QtWidgets.QDateEdit(StudentBox)
        self.dateEdit.setGeometry(QtCore.QRect(160, 160, 201, 30))
        self.dateEdit.setObjectName("dateEdit")
        self.huomingEdit = QtWidgets.QLineEdit(StudentBox)
        self.huomingEdit.setGeometry(QtCore.QRect(160, 195, 201, 30))
        self.huomingEdit.setClearButtonEnabled(True)
        self.huomingEdit.setObjectName("huomingEdit")
        self.jingzhongEdit = QtWidgets.QLineEdit(StudentBox)
        self.jingzhongEdit.setGeometry(QtCore.QRect(160, 230, 201, 30))
        self.jingzhongEdit.setClearButtonEnabled(True)
        self.jingzhongEdit.setObjectName("jingzhongEdit")
        self.maozhongEdit = QtWidgets.QLineEdit(StudentBox)
        self.maozhongEdit.setGeometry(QtCore.QRect(160, 265, 201, 30))
        self.maozhongEdit.setClearButtonEnabled(True)
        self.maozhongEdit.setObjectName("maozhongEdit")
        self.baolaijianshuEdit = QtWidgets.QLineEdit(StudentBox)
        self.baolaijianshuEdit.setGeometry(QtCore.QRect(160, 300, 201, 30))
        self.baolaijianshuEdit.setClearButtonEnabled(True)
        self.baolaijianshuEdit.setObjectName("baolaijianshuEdit")
        self.jianzhongEdit = QtWidgets.QLineEdit(StudentBox)
        self.jianzhongEdit.setGeometry(QtCore.QRect(160, 335, 201, 30))
        self.jianzhongEdit.setClearButtonEnabled(True)
        self.jianzhongEdit.setObjectName("jianzhongEdit")        
        self.yuanguihaoEdit = QtWidgets.QLineEdit(StudentBox)
        self.yuanguihaoEdit.setGeometry(QtCore.QRect(160, 370, 201, 30))
        self.yuanguihaoEdit.setClearButtonEnabled(True)
        self.yuanguihaoEdit.setObjectName("yuanguihaoEdit")
        self.zhongweiEdit = QtWidgets.QDateEdit(StudentBox)
        self.zhongweiEdit.setGeometry(QtCore.QRect(160, 405, 201, 30))
        self.zhongweiEdit.setObjectName("zhongweiEdit")
        self.jiweiEdit = QtWidgets.QDateEdit(StudentBox)
        self.jiweiEdit.setGeometry(QtCore.QRect(160, 440, 201, 30))
        self.jiweiEdit.setObjectName("jiweiEdit")
        self.fangxiangriqiEdit = QtWidgets.QDateEdit(StudentBox)
        self.fangxiangriqiEdit.setGeometry(QtCore.QRect(160, 475, 201, 30))
        self.fangxiangriqiEdit.setObjectName("fangxiangriqiEdit")
        self.notes1Edit = QtWidgets.QPlainTextEdit(StudentBox)
        self.notes1Edit.setGeometry(QtCore.QRect(160, 510, 201, 100))
        self.notes1Edit.setObjectName("notes1Edit")
        self.zhongweiriqiEdit = QtWidgets.QDateEdit(StudentBox)
        self.zhongweiriqiEdit.setGeometry(QtCore.QRect(160, 615, 201, 30))
        self.zhongweiriqiEdit.setObjectName("zhongweiriqiEdit")
        self.bangzhongEdit = QtWidgets.QLineEdit(StudentBox)
        self.bangzhongEdit.setGeometry(QtCore.QRect(160, 650, 201, 30))
        self.bangzhongEdit.setClearButtonEnabled(True)
        self.bangzhongEdit.setObjectName("bangzhongEdit")
        self.notes2Edit = QtWidgets.QPlainTextEdit(StudentBox)
        self.notes2Edit.setGeometry(QtCore.QRect(600, 55, 200, 135))
        self.notes2Edit.setObjectName("notes2Edit")
        self.guoguiriqi1Edit = QtWidgets.QDateEdit(StudentBox)
        self.guoguiriqi1Edit.setGeometry(QtCore.QRect(600, 195, 200, 30))
        self.guoguiriqi1Edit.setObjectName("guoguiriqi1Edit")
        self.guoguiguihao1Edit = QtWidgets.QLineEdit(StudentBox)
        self.guoguiguihao1Edit.setGeometry(QtCore.QRect(600, 230, 200, 30))
        self.guoguiguihao1Edit.setClearButtonEnabled(True)
        self.guoguiguihao1Edit.setObjectName("guoguiguihao1Edit")
        self.guoguiriqi2Edit = QtWidgets.QDateEdit(StudentBox)
        self.guoguiriqi2Edit.setGeometry(QtCore.QRect(600, 265, 200, 30))
        self.guoguiriqi2Edit.setObjectName("guoguiriqi2Edit")
        self.guoguiguihao2Edit = QtWidgets.QLineEdit(StudentBox)
        self.guoguiguihao2Edit.setGeometry(QtCore.QRect(600, 300, 200, 30))
        self.guoguiguihao2Edit.setClearButtonEnabled(True)
        self.guoguiguihao2Edit.setObjectName("guoguiguihao2Edit")
        self.guoguiriqi3Edit = QtWidgets.QDateEdit(StudentBox)
        self.guoguiriqi3Edit.setGeometry(QtCore.QRect(600, 335, 200, 30))
        self.guoguiriqi3Edit.setObjectName("guoguiriqi3Edit")
        self.guoguiguihao3Edit = QtWidgets.QLineEdit(StudentBox)
        self.guoguiguihao3Edit.setGeometry(QtCore.QRect(600, 370, 200, 30))
        self.guoguiguihao3Edit.setClearButtonEnabled(True)
        self.guoguiguihao3Edit.setObjectName("guoguiguihao3Edit")
        self.guoguiriqi4Edit = QtWidgets.QDateEdit(StudentBox)
        self.guoguiriqi4Edit.setGeometry(QtCore.QRect(600, 405, 200, 30))
        self.guoguiriqi4Edit.setObjectName("guoguiriqi4Edit")
        self.chukouguihaoEdit = QtWidgets.QLineEdit(StudentBox)
        self.chukouguihaoEdit.setGeometry(QtCore.QRect(600, 440, 200, 30))
        self.chukouguihaoEdit.setClearButtonEnabled(True)
        self.chukouguihaoEdit.setObjectName("chukouguihaoEdit")
        self.shishoujianshuEdit = QtWidgets.QLineEdit(StudentBox)
        self.shishoujianshuEdit.setGeometry(QtCore.QRect(600, 475, 200, 30))
        self.shishoujianshuEdit.setClearButtonEnabled(True)
        self.shishoujianshuEdit.setObjectName("shishoujianshuEdit")
        self.baozhuangEdit = QtWidgets.QLineEdit(StudentBox)
        self.baozhuangEdit.setGeometry(QtCore.QRect(600, 510, 200, 30))
        self.baozhuangEdit.setClearButtonEnabled(True)
        self.baozhuangEdit.setObjectName("baozhuangEdit")
        self.chuhuoriqi1Edit = QtWidgets.QDateEdit(StudentBox)
        self.chuhuoriqi1Edit.setGeometry(QtCore.QRect(1060, 55, 200, 30))
        self.chuhuoriqi1Edit.setObjectName("chuhuoriqi1Edit")
        self.chuhuojianshu1Edit = QtWidgets.QLineEdit(StudentBox)
        self.chuhuojianshu1Edit.setGeometry(QtCore.QRect(1060, 90, 200, 30))
        self.chuhuojianshu1Edit.setClearButtonEnabled(True)
        self.chuhuojianshu1Edit.setObjectName("chuhuojianshu1Edit")
        self.chuhuoguihao1Edit = QtWidgets.QLineEdit(StudentBox)
        self.chuhuoguihao1Edit.setGeometry(QtCore.QRect(1060, 125, 200, 30))
        self.chuhuoguihao1Edit.setClearButtonEnabled(True)
        self.chuhuoguihao1Edit.setObjectName("chuhuoguihao1Edit")
        self.chuhuoriqi2Edit = QtWidgets.QDateEdit(StudentBox)
        self.chuhuoriqi2Edit.setGeometry(QtCore.QRect(1060, 160, 200, 30))
        self.chuhuoriqi2Edit.setObjectName("chuhuoriqi2Edit")
        self.chuhuojianshu2Edit = QtWidgets.QLineEdit(StudentBox)
        self.chuhuojianshu2Edit.setGeometry(QtCore.QRect(1060, 195, 200, 30))
        self.chuhuojianshu2Edit.setClearButtonEnabled(True)
        self.chuhuojianshu2Edit.setObjectName("chuhuojianshu2Edit")
        self.chuhuoguihao2Edit = QtWidgets.QLineEdit(StudentBox)
        self.chuhuoguihao2Edit.setGeometry(QtCore.QRect(1060, 230, 200, 30))
        self.chuhuoguihao2Edit.setClearButtonEnabled(True)
        self.chuhuoguihao2Edit.setObjectName("chuhuoguihao2Edit")
        self.chuhuoriqi3Edit = QtWidgets.QDateEdit(StudentBox)
        self.chuhuoriqi3Edit.setGeometry(QtCore.QRect(1060, 265, 200, 30))
        self.chuhuoriqi3Edit.setObjectName("chuhuoriqi3Edit")
        self.chuhuojianshu3Edit = QtWidgets.QLineEdit(StudentBox)
        self.chuhuojianshu3Edit.setGeometry(QtCore.QRect(1060, 300, 200, 30))
        self.chuhuojianshu3Edit.setClearButtonEnabled(True)
        self.chuhuojianshu3Edit.setObjectName("chuhuojianshu3Edit")
        self.chuhuoguihao3Edit = QtWidgets.QLineEdit(StudentBox)
        self.chuhuoguihao3Edit.setGeometry(QtCore.QRect(1060, 335, 200, 30))
        self.chuhuoguihao3Edit.setClearButtonEnabled(True)
        self.chuhuoguihao3Edit.setObjectName("chuhuoguihao3Edit")
        self.chuhuoriqi4Edit = QtWidgets.QDateEdit(StudentBox)
        self.chuhuoriqi4Edit.setGeometry(QtCore.QRect(1060, 370, 200, 30))
        self.chuhuoriqi4Edit.setObjectName("chuhuoriqi4Edit")
        self.chuhuojianshu4Edit = QtWidgets.QLineEdit(StudentBox)
        self.chuhuojianshu4Edit.setGeometry(QtCore.QRect(1060, 405, 200, 30))
        self.chuhuojianshu4Edit.setClearButtonEnabled(True)
        self.chuhuojianshu4Edit.setObjectName("chuhuojianshu4Edit")
        self.chuhuoguihao4Edit = QtWidgets.QLineEdit(StudentBox)
        self.chuhuoguihao4Edit.setGeometry(QtCore.QRect(1060, 440, 200, 30))
        self.chuhuoguihao4Edit.setClearButtonEnabled(True)
        self.chuhuoguihao4Edit.setObjectName("chuhuoguihao4Edit")
        self.chuhuoriqi5Edit = QtWidgets.QDateEdit(StudentBox)
        self.chuhuoriqi5Edit.setGeometry(QtCore.QRect(1060, 475, 200, 30))
        self.chuhuoriqi5Edit.setObjectName("chuhuoriqi5Edit")
        self.chuhuojianshu5Edit = QtWidgets.QLineEdit(StudentBox)
        self.chuhuojianshu5Edit.setGeometry(QtCore.QRect(1060, 510, 200, 30))
        self.chuhuojianshu5Edit.setClearButtonEnabled(True)
        self.chuhuojianshu5Edit.setObjectName("chuhuojianshu5Edit")
        self.chuhuoguihao5Edit = QtWidgets.QLineEdit(StudentBox)
        self.chuhuoguihao5Edit.setGeometry(QtCore.QRect(1060, 545, 200, 30))
        self.chuhuoguihao5Edit.setClearButtonEnabled(True)
        self.chuhuoguihao5Edit.setObjectName("chuhuoguihao5Edit")

        self.jiedanriqiEdit = QtWidgets.QDateEdit(StudentBox)
        self.jiedanriqiEdit.setGeometry(QtCore.QRect(1060, 580, 200, 30))
        self.jiedanriqiEdit.setObjectName("jiedanriqiEdit")
        self.jiesuanzhuangtaiEdit = QtWidgets.QLineEdit(StudentBox)
        self.jiesuanzhuangtaiEdit.setGeometry(QtCore.QRect(1060, 615, 200, 30))
        self.jiesuanzhuangtaiEdit.setClearButtonEnabled(True)
        self.jiesuanzhuangtaiEdit.setObjectName("jiesuanzhuangtaiEdit")
        self.notes3Edit = QtWidgets.QPlainTextEdit(StudentBox)
        self.notes3Edit.setGeometry(QtCore.QRect(190, 700, 750, 70))
        self.notes3Edit.setObjectName("user_notesEdit")

        self.notes4Edit = QtWidgets.QPlainTextEdit(StudentBox)
        self.notes4Edit.setGeometry(QtCore.QRect(190, 780, 750, 70))
        self.notes4Edit.setObjectName("admin_notesEdit")

        self.okButton = QtWidgets.QPushButton(StudentBox)
        self.okButton.setGeometry(QtCore.QRect(980, 700, 120, 80))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(StudentBox)
        self.cancelButton.setGeometry(QtCore.QRect(1120, 700, 120, 80))
        self.cancelButton.setObjectName("cancelButton")
        self.msg = QtWidgets.QLabel(StudentBox)
        self.msg.setGeometry(QtCore.QRect(10, 10, 100, 30))
        self.msg.setAlignment(QtCore.Qt.AlignCenter)
        self.msg.setObjectName("msg")

        self.retranslateUi(StudentBox)
        QtCore.QMetaObject.connectSlotsByName(StudentBox)
        StudentBox.setTabOrder(self.indexEdit, self.clientEdit)
        StudentBox.setTabOrder(self.clientEdit, self.fuhuoEdit)
        StudentBox.setTabOrder(self.fuhuoEdit, self.dateEdit)
        StudentBox.setTabOrder(self.dateEdit, self.huomingEdit)
        StudentBox.setTabOrder(self.huomingEdit, self.jingzhongEdit)
        StudentBox.setTabOrder(self.jingzhongEdit, self.maozhongEdit)
        StudentBox.setTabOrder(self.maozhongEdit, self.baolaijianshuEdit)
        StudentBox.setTabOrder(self.baolaijianshuEdit, self.jianzhongEdit)
        StudentBox.setTabOrder(self.jianzhongEdit, self.yuanguihaoEdit)
        StudentBox.setTabOrder(self.yuanguihaoEdit, self.zhongweiEdit)
        StudentBox.setTabOrder(self.zhongweiEdit, self.jiweiEdit)
        StudentBox.setTabOrder(self.jiweiEdit, self.fangxiangriqiEdit)
        StudentBox.setTabOrder(self.fangxiangriqiEdit, self.notes1Edit)
        StudentBox.setTabOrder(self.notes1Edit, self.zhongweiEdit)
        StudentBox.setTabOrder(self.zhongweiEdit, self.bangzhongEdit)
        StudentBox.setTabOrder(self.bangzhongEdit, self.notes2Edit)
        StudentBox.setTabOrder(self.notes2Edit, self.guoguiriqi1Edit)
        StudentBox.setTabOrder(self.guoguiriqi1Edit, self.guoguiguihao1Edit)
        StudentBox.setTabOrder(self.guoguiguihao1Edit, self.guoguiriqi2Edit)
        StudentBox.setTabOrder(self.guoguiriqi2Edit, self.guoguiguihao2Edit)
        StudentBox.setTabOrder(self.guoguiguihao2Edit, self.guoguiriqi3Edit)
        StudentBox.setTabOrder(self.guoguiriqi3Edit, self.guoguiguihao3Edit)
        StudentBox.setTabOrder(self.guoguiguihao3Edit, self.guoguiriqi4Edit)
        StudentBox.setTabOrder(self.guoguiriqi4Edit, self.chukouguihaoEdit)
        StudentBox.setTabOrder(self.chukouguihaoEdit, self.shishoujianshuEdit)
        StudentBox.setTabOrder(self.shishoujianshuEdit, self.baozhuangEdit)
        StudentBox.setTabOrder(self.baozhuangEdit, self.chuhuoriqi1Edit)
        StudentBox.setTabOrder(self.chuhuoriqi1Edit, self.chuhuojianshu1Edit)
        StudentBox.setTabOrder(self.chuhuojianshu1Edit, self.chuhuoguihao1Edit)
        StudentBox.setTabOrder(self.chuhuoguihao1Edit, self.chuhuoriqi2Edit)
        StudentBox.setTabOrder(self.chuhuoriqi2Edit, self.chuhuojianshu2Edit)
        StudentBox.setTabOrder(self.chuhuojianshu2Edit, self.chuhuoguihao2Edit)
        StudentBox.setTabOrder(self.chuhuoguihao2Edit, self.chuhuoriqi3Edit)
        StudentBox.setTabOrder(self.chuhuoriqi3Edit, self.chuhuojianshu3Edit)
        StudentBox.setTabOrder(self.chuhuojianshu3Edit, self.chuhuoguihao3Edit)
        StudentBox.setTabOrder(self.chuhuoguihao3Edit, self.chuhuoriqi4Edit)
        StudentBox.setTabOrder(self.chuhuoriqi4Edit, self.chuhuojianshu4Edit)
        StudentBox.setTabOrder(self.chuhuojianshu4Edit, self.chuhuoguihao4Edit)
        StudentBox.setTabOrder(self.chuhuoguihao4Edit, self.chuhuoriqi5Edit)
        StudentBox.setTabOrder(self.chuhuoriqi5Edit, self.chuhuojianshu5Edit)
        StudentBox.setTabOrder(self.chuhuojianshu5Edit, self.chuhuoguihao5Edit)
        StudentBox.setTabOrder(self.chuhuoguihao5Edit, self.jiedanriqiEdit)
        StudentBox.setTabOrder(self.jiedanriqiEdit, self.jiesuanzhuangtaiEdit)
        StudentBox.setTabOrder(self.jiesuanzhuangtaiEdit, self.notes3Edit)
        StudentBox.setTabOrder(self.notes3Edit, self.notes4Edit)
        StudentBox.setTabOrder(self.notes4Edit, self.okButton)
        StudentBox.setTabOrder(self.okButton, self.cancelButton)

    def retranslateUi(self, StudentBox):
        _translate = QtCore.QCoreApplication.translate
        StudentBox.setWindowTitle(_translate("StudentBox", "报单信息盒"))
        self.label.setText(_translate("StudentBox", "序號"))
        self.label_2.setText(_translate("StudentBox", "客戶"))
        self.label_3.setText(_translate("StudentBox", "付貨人"))
        self.label_4.setText(_translate("StudentBox", "收單日期"))
        self.label_5.setText(_translate("StudentBox", "貨名"))
        self.label_6.setText(_translate("StudentBox", "客戶净重"))
        self.label_7.setText(_translate("StudentBox", "客戶毛重"))
        self.label_8.setText(_translate("StudentBox", "報來件數"))
        self.label_9.setText(_translate("StudentBox", "件重"))
        self.label_10.setText(_translate("StudentBox", "原櫃號"))
        self.label_11.setText(_translate("StudentBox", "重尾"))
        self.label_12.setText(_translate("StudentBox", "吉尾"))
        self.label_13.setText(_translate("StudentBox", "放箱日期"))
        self.label_14.setText(_translate("StudentBox", "拖重備注"))
        self.label_15.setText(_translate("StudentBox", "拖重日期"))
        self.label_16.setText(_translate("StudentBox", "實收磅重"))
        self.label_17.setText(_translate("StudentBox", "過櫃備注"))
        self.label_18.setText(_translate("StudentBox", "過軌日期1"))
        self.label_19.setText(_translate("StudentBox", "過櫃櫃號1"))
        self.label_20.setText(_translate("StudentBox", "過櫃日期2"))
        self.label_21.setText(_translate("StudentBox", "過櫃櫃號2"))
        self.label_22.setText(_translate("StudentBox", "過櫃日期3"))
        self.label_23.setText(_translate("StudentBox", "過櫃櫃號3"))
        self.label_24.setText(_translate("StudentBox", "過櫃日期4"))
        self.label_25.setText(_translate("StudentBox", "出口櫃號"))
        self.label_26.setText(_translate("StudentBox", "實收件數"))
        self.label_27.setText(_translate("StudentBox", "包裝"))
        self.label_28.setText(_translate("StudentBox", "出貨日期1"))
        self.label_29.setText(_translate("StudentBox", "出貨件數1"))
        self.label_30.setText(_translate("StudentBox", "出貨櫃號1"))
        self.label_31.setText(_translate("StudentBox", "出貨日期2"))
        self.label_32.setText(_translate("StudentBox", "出貨件數2"))
        self.label_33.setText(_translate("StudentBox", "出貨櫃號2"))
        self.label_34.setText(_translate("StudentBox", "出貨日期3"))
        self.label_35.setText(_translate("StudentBox", "出貨件數3"))
        self.label_36.setText(_translate("StudentBox", "出貨櫃號3"))
        self.label_37.setText(_translate("StudentBox", "出貨日期4"))
        self.label_38.setText(_translate("StudentBox", "出貨件數4"))
        self.label_39.setText(_translate("StudentBox", "出貨櫃號4"))
        self.label_40.setText(_translate("StudentBox", "出貨日期5"))
        self.label_41.setText(_translate("StudentBox", "出貨件數5"))
        self.label_42.setText(_translate("StudentBox", "出貨櫃號5"))
        self.label_43.setText(_translate("StudentBox", "結單日期"))
        self.label_44.setText(_translate("StudentBox", "結算狀態"))
        self.label_45.setText(_translate("StudentBox", "出貨備注"))
        self.label_46.setText(_translate("StudentBox", "訂單備注"))
        self.okButton.setText(_translate("StudentBox", "确定"))
        self.cancelButton.setText(_translate("StudentBox", "取消"))
        self.msg.setText(_translate("StudentBox", "提示信息"))

        #StudentBox.setWindowOpacity(0.98)
        #StudentBox.setWindowFlag(QtCore.Qt.FramelessWindowHint)
